- name: Listen for newly added ConfigMap resources
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: ServiceAccount
        namespace: test-cm
  rules:
    - name: Notify
      condition: event.type == "ADDED"
      action:
        run_playbook:
          name: get-sa-token.yml

